"""Update tournament

Revision ID: 6037da22600e
Revises: a572b0103478
Create Date: 2026-02-25 20:57:55.027541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6037da22600e'
down_revision: Union[str, Sequence[str], None] = 'a572b0103478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.alter_column('tournaments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tournaments', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tournaments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tournaments', 'start_date')
    op.drop_column('tournaments', 'description')
    # ### end Alembic commands ###
