"""soporte para zonas horarias

Revision ID: a429744551f3
Revises: 4ba3b630d4d3
Create Date: 2026-02-18 18:10:45.515497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a429744551f3'
down_revision: Union[str, Sequence[str], None] = '4ba3b630d4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('team_members', sa.Column('joined_at', sa.DateTime(), nullable=True))
    op.drop_column('team_members', 'status')
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teams', 'captain_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'captain_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('teams', 'created_at')
    op.add_column('team_members', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('team_members', 'joined_at')
    op.drop_column('team_members', 'id')
    # ### end Alembic commands ###
