"""Update user

Revision ID: a572b0103478
Revises: 02cfb68570e0
Create Date: 2026-02-25 12:43:27.000174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a572b0103478'
down_revision: Union[str, Sequence[str], None] = '02cfb68570e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_country_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('discord_id', sa.String(), nullable=True))
    op.drop_column('users', 'whatsapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'discord_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'phone_country_code')
    # ### end Alembic commands ###
